//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_sanicball_Move;
        
        private static SteamVR_Action_Vector2 p_sanicball_Look;
        
        private static SteamVR_Action_Boolean p_sanicball_Jump;
        
        private static SteamVR_Action_Boolean p_sanicball_Respawn;
        
        private static SteamVR_Action_Boolean p_sanicball_Brake;
        
        private static SteamVR_Action_Boolean p_sanicball_Next_Track;
        
        private static SteamVR_Action_Boolean p_sanicball_Click;
        
        private static SteamVR_Action_Boolean p_sanicball_Menu;
        
        private static SteamVR_Action_Boolean p_sanicball_Select;
        
        private static SteamVR_Action_Pose p_sanicball_Hands;
        
        public static SteamVR_Action_Vector2 sanicball_Move
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 sanicball_Look
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Look.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Jump
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Respawn
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Respawn.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Brake
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Next_Track
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Next_Track.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Click
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Menu
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sanicball_Select
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Select.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose sanicball_Hands
        {
            get
            {
                return SteamVR_Actions.p_sanicball_Hands.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.sanicball_Move,
                    SteamVR_Actions.sanicball_Look,
                    SteamVR_Actions.sanicball_Jump,
                    SteamVR_Actions.sanicball_Respawn,
                    SteamVR_Actions.sanicball_Brake,
                    SteamVR_Actions.sanicball_Next_Track,
                    SteamVR_Actions.sanicball_Click,
                    SteamVR_Actions.sanicball_Menu,
                    SteamVR_Actions.sanicball_Select,
                    SteamVR_Actions.sanicball_Hands};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.sanicball_Move,
                    SteamVR_Actions.sanicball_Look,
                    SteamVR_Actions.sanicball_Jump,
                    SteamVR_Actions.sanicball_Respawn,
                    SteamVR_Actions.sanicball_Brake,
                    SteamVR_Actions.sanicball_Next_Track,
                    SteamVR_Actions.sanicball_Click,
                    SteamVR_Actions.sanicball_Menu,
                    SteamVR_Actions.sanicball_Select,
                    SteamVR_Actions.sanicball_Hands};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.sanicball_Hands};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.sanicball_Jump,
                    SteamVR_Actions.sanicball_Respawn,
                    SteamVR_Actions.sanicball_Brake,
                    SteamVR_Actions.sanicball_Next_Track,
                    SteamVR_Actions.sanicball_Click,
                    SteamVR_Actions.sanicball_Menu,
                    SteamVR_Actions.sanicball_Select};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.sanicball_Move,
                    SteamVR_Actions.sanicball_Look};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.sanicball_Move,
                    SteamVR_Actions.sanicball_Look,
                    SteamVR_Actions.sanicball_Jump,
                    SteamVR_Actions.sanicball_Respawn,
                    SteamVR_Actions.sanicball_Brake,
                    SteamVR_Actions.sanicball_Next_Track,
                    SteamVR_Actions.sanicball_Click,
                    SteamVR_Actions.sanicball_Menu,
                    SteamVR_Actions.sanicball_Select};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_sanicball_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/sanicball/in/Move")));
            SteamVR_Actions.p_sanicball_Look = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/sanicball/in/Look")));
            SteamVR_Actions.p_sanicball_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Jump")));
            SteamVR_Actions.p_sanicball_Respawn = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Respawn")));
            SteamVR_Actions.p_sanicball_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Brake")));
            SteamVR_Actions.p_sanicball_Next_Track = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Next Track")));
            SteamVR_Actions.p_sanicball_Click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Click")));
            SteamVR_Actions.p_sanicball_Menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Menu")));
            SteamVR_Actions.p_sanicball_Select = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/sanicball/in/Select")));
            SteamVR_Actions.p_sanicball_Hands = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/sanicball/in/Hands")));
        }
    }
}
