//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_sanicball : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.sanicball_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.sanicball_Look;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.sanicball_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Respawn
        {
            get
            {
                return SteamVR_Actions.sanicball_Respawn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Brake
        {
            get
            {
                return SteamVR_Actions.sanicball_Brake;
            }
        }
        
        public virtual SteamVR_Action_Boolean Next_Track
        {
            get
            {
                return SteamVR_Actions.sanicball_Next_Track;
            }
        }
        
        public virtual SteamVR_Action_Boolean Click
        {
            get
            {
                return SteamVR_Actions.sanicball_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.sanicball_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.sanicball_Select;
            }
        }
        
        public virtual SteamVR_Action_Pose Hands
        {
            get
            {
                return SteamVR_Actions.sanicball_Hands;
            }
        }
    }
}
